### ISSUE TITLE
The chicken and the egg 🐔🥚

### ISSUE THREAD

**Issue by yeqbfgxjiq** [aragoncoop/coop-dao-docs#20] opened 2019-05-01 06:40 UTC
Aragon is bird themed. The Aragon Cooperative exists to help the community understand, engage with, and build on Aragon. The coop is an incubator, and as such it seems natural that the chicken and the egg would be our natural mascots. Puns ahoy!

**Comment by sepu85** [comment] 2019-05-01 18:42
personally, I don't like this idea, basically because I don't see the Coop being an incubator (although, I'm curious about what made you having such perception)...

Cool to have a different bird for us, but I would say the mascot should be an [sterling](https://www.youtube.com/watch?v=dedVszDI9aE) rather than a chicken, that represents better our community, descentralized, autonomous and signaling driven approach... But this is a miscellaneous thing/decision that worth to be proposed and discussed once we have a governance framework, not earlier...

have you read the [Coop first Manifesto proposal](https://forum.aragon.org/t/aragon-coop-dao-a-minimum-viable-manifesto-mvm/690/3) BTW?

**Comment by yeqbfgxjiq** [comment] 2019-05-01 19:20
@sepu85  Thanks for the feedback. I started thinking in this direction because there were several discussions on the forum around funding small scale community driven projects. I'm starting to see that might not be the priority though, in which case I might spin off The Coop as a separate project focused on developer UX and shipping code vs signalling and community discussions.

**Comment by sepu85** [comment] 2019-05-01 19:35
@burrrata you might be referring to the the [AGP-10 Community Funding DAO](https://forum.aragon.org/t/how-to-make-proposals-to-the-community-funding-dao/697), which is a different thing from the Coop, there have been conversations about including a funding proposal curation process within the scope of the Coop, but that might need a new AGP for next ANV....

**Comment by yeqbfgxjiq** [comment] 2019-05-01 23:15
There's lot of proposals in lots of places, most of them vague, and most of them mixed together in my head. With the Community Funding DAO and the Coop Workflow I thought the general trend was to move towards capital allocation via community governance. If that's not the case though, I really want to understand the tangible vision people have for the coop. That's why I'm working on my proposals so fiercely and I hope people work on theirs too so that I can have a better idea of what people want and what they're thinking. When you said that you don't see the coop as being an incubator, what do you see the coop as being? What's do you see as it's purpose and what do you want it to do?

**Comment by sepu85** [comment] 2019-05-01 23:41
> I thought the general trend was to move towards capital allocation via community governance

that's where we are right now after AGP-40 got approved, but that's the current state for something that was originally proposed last november, there's a bit of background history that I have the feeling you have skipped. It is awesome that people like you show such and enthusiasm, I think you have earned pretty well you membership token! What I'm a bit afraid about is that having now these much proposals would only add entropy to the governance framework definition. My view is pretty simple: first we work on how we want to govern the proposals we want to implement (as the work we will do and the resources we will manage) and then we will focus on proposal discussions, if we do otherwise, we will face only chaos ;-)

**Comment by julianbrooks** [comment] 2019-05-10 13:36
I'm gonna close this issue. The chicken/egg thing seems to have been spun out into a standalone project by @burrrata (which is cool and we wish him all the best with that). Also really hope that @burrrata will continue his involvement with the Coop. Be great to have some discussion on what that might be a.s.a.p.. But yeah, more widely, the current coop github is kinda a mess with conflicting info and files scattered in various locations. Maybe the 3 of us (& the wider coop crew too ideally) could get our heads together and consider how this may start to function a little more as intended...

**Closed as completed by julianbrooks** 2019-05-10 13:36 UTC
Labels: proposal
